# Builds all the projects in the solution...
.PHONY: all_projects
all_projects: PSI_Linux 

# Builds project 'SM2_COOP'...
.PHONY: PSI_Linux
PSI_Linux: 
	make --directory="PSI_Linux/" --file=PSI_Linux.makefile

# Cleans all projects...
.PHONY: clean
clean:
	make --directory="PSI_Linux/" --file=PSI_Linux.makefile clean

