/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_rongan_PSINativeRA */

#ifndef _Included_com_rongan_PSINativeRA
#define _Included_com_rongan_PSINativeRA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rongan_PSINativeRA
 * Method:    data2Point
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rongan_PSINativeRA_data2Point
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rongan_PSINativeRA
 * Method:    pointBlindWithRA
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rongan_PSINativeRA_pointBlindWithRA
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_rongan_PSINativeRA
 * Method:    getInverseRA
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rongan_PSINativeRA_getInverseRA
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rongan_PSINativeRA
 * Method:    sm3Hash
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rongan_PSINativeRA_sm3Hash
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rongan_PSINativeRA
 * Method:    getIntersect
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rongan_PSINativeRA_getIntersect
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray);
/*
 * Class:     com_rongan_PSINativeRA
 * Method:    getRandomString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rongan_PSINativeRA_getRandomString
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rongan_PSINativeRA
 * Method:    disorderStrings
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rongan_PSINativeRA_disorderStrings
  (JNIEnv *, jclass, jobjectArray, jobjectArray);
#ifdef __cplusplus
}
#endif
#endif
